# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Hu Xiuhan
email: huxiuhan@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Hu Xiuhan's Homepage
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://huxiuhan.com" # the base hostname & protocol for your site
github_username:  huxiuhan
linkedin_pagename: xiuhanhu
facebook_username: xiuhan.hu
# Build settings
markdown: kramdown
